### PR TITLE
Added Rust implementation

### PR DESCRIPTION
**Pull request by gsingh93**
This commit makes use of Rust's built in benchmarking functions. Thus, executing this binary will take longer than a single run of the code, as it will be executed multiple times. The code will output the average time in nanoseconds. Details on how to run it are in the file.

### CODE REVIEW

**Comment by MikeMirzayanov** [comment]
Thanks. Can you write exactly equal code as C++? Benchmarks can be used in automatic mode,  so they should do exactly the same. It can do more with a special flag.

**Comment by gsingh93** [comment]
Just to be clear, everything is fine except I should manually time it, not use Rust's benchmark functions? If so, sure, I'll fix it in the morning.

**Comment by gsingh93** [comment]
Ok, so the way Rust works is it pushes non-core functionality (like timing things) into packages that aren't part of the standard distribution but are still maintained by the Rust team. You pull those packages with the package manager Cargo (which is installed with Rust), so I've switched the build process to using that so I can access the timing functions. Hopefully that's not a problem.

So the build process is now just `cargo build`. This will build with the highest optimization level. To run the binary, you can either do `cargo run` or manually execute the binary in `./target/heap`

**Comment by gsingh93** [comment]
I've updated it to make it simpler and squashed all the commits into one. To build, run
```
rustc -C opt-level=3 main.rs
```

**Comment by gsingh93** [comment]
The benchmark now uses Cargo, as the `time` crate is required. Rust 1.0 has been released, there should be no problem merging this now.

**Comment by gsingh93** [comment]
@MikeMirzayanov Are you still planning on adding Rust support? It's been a while...

**Comment by Enamex** [comment]
What problems still remain? I might be able to help/know some who could help :)

**Comment by gsingh93** [comment]
No problems remain. @MikeMirzayanov has just been completely unresponsive to both my Github comments and my emails.

**Comment by razvan-panda** [comment]
@gsingh93 I think he wants the commit to be C++ code, see his comment above.

**Comment by gsingh93** [comment]
That is currently impossible without adding the `time` crate, and that *should not* be a blocker for this PR.

**Pull request merged**
